### ISSUE TITLE
Command line arguments specification with '=' doesn't work

### ISSUE THREAD

**Issue by dj1vs** [max-niederman/ttyper#135]
Example:

1. Doesn't work:
```bash
ttyper --language-file=~/.config/ttyper/words
```

2. Executes well:
```bash
ttyper --language-file ~/.config/ttyper/words
```

**Comment by Axlefublr** [comment]
Could you please elaborate on why you want that `=` feature?

**Comment by dj1vs** [comment]
Because this is common behaviour for a lot of console applications. For example, podman, or gcc (first things that came to my mind).  I think that many people are already used to it.

**Comment by max-niederman** [comment]
ttyper does support this option syntax. This example doesn't work because your shell isn't expanding the `~` character to your home directory. If you try with an absolute path it will work.

It is *possible* to make this corner case work by expanding tildes within ttyper, but I'm not a huge fan of doing this because
1. relative file paths beginning with `~` are valid, so there would have to be some bespoke, nonstandard way to escape these file paths.
2. This is generally understood to be the shell's responsibility.

**Comment by dj1vs** [comment]
Ok, now I get it. Didn't think of it this way. Thanks!
