### ISSUE TITLE
[ Request ] Add sentence support

### ISSUE THREAD

**Issue by mrbooshehri** [max-niederman/ttyper#20]
Hi and thanks for amazing program. I just want to ask, is it possible to add sentence support to ttyper? 
I mean pass this kind of files as the input:
```
Hi this is a sentence.
We have another one here.
It's possible to have another one here.
```
Probable solution: Use return key as line delimiter and blank space (also other punctuations) as word delimiter.

**Comment by max-niederman** [comment]
This is possible as of 2b34d649cf40142c90c3a9720f15e9efb592e7d4, and will be available on crates.io soon. It works by interpreting the space character literally when it is correct for the word, so words can have spaces in them and therefore not really be "words" at all.
So if you passed a file with sentences on each line as in your example you would type each sentence out as a whole rather than as multiple words.

This isn't a perfect solution as it makes it considerably harder to use the input file feature on preexisting text, as word length is dependent on the line length. There should probably be options to split the input file into words differently in the future.
