### ISSUE TITLE
Cross-platform whole-word deletion

### ISSUE THREAD

**Issue by brian6932** [max-niederman/ttyper#44]
I use this a lot when typing, and was caught off guard when there was no way to delete a whole word.

**Comment by max-niederman** [comment]
This actually is supported but is pretty platform specific because different terminals handle the backspace key differently, which is [kind of a pain](https://tldp.org/HOWTO/Keyboard-and-Console-HOWTO-5.html).

Right now, we handle `Ctrl-H` which all the terminals I've tested on sends for physically pressing `Ctrl-Backspace`.

I can't easily test on your specific platform but if you'd like you can submit a PR which modifies [the relevant code](https://github.com/max-niederman/ttyper/blob/4ae4586febc7b65a1c56eeba179e27220b5fbf72/src/test/mod.rs#L56).

**Comment by brian6932** [comment]
@max-niederman is there a reason this was closed? it's not exactly resolved,

**Comment by brian6932** [comment]
If the reason you closed this was because I forgot to specify my platform:
I'm on Windows 10 and shell is pwsh v7.2.2

**Comment by brian6932** [comment]
For the record, this only deletes a single character for me
