### ISSUE TITLE
Feature Request: Pipe text into ttyper

### ISSUE THREAD

**Issue by brian6932** [max-niederman/ttyper#74]
Would be nice if you could pipe text directly into ttyper, as opposed to having to make it a file first, could allow for some cool mixups, like requesting a random quote, and then typing that out through ttyper.

Example:
```zsh
curl -sSL https://api.quotable.io/random | jq -r .content | ttyper
```
Side note, currently text doesn't seem to wrap to term size properly, that should be fixed before this would be added ofc
![image](https://user-images.githubusercontent.com/18603393/227854907-c5b3c63d-56dc-486c-8fbd-d73131b307ea.png)
![image](https://user-images.githubusercontent.com/18603393/227855001-e0ecb00e-e691-47a9-819c-8e5c0403a28e.png)

**Comment by adrianncovaci** [comment]
Is this available?

**Comment by max-niederman** [comment]
This is already supported. You just need to set the input file to `/dev/stdin`:

```bash
curl -sSL https://api.quotable.io/random | jq -r .content | ttyper /dev/stdin
```
Or, alternatively, you can use process substitution:

```bash
ttyper <(curl -sSL https://api.quotable.io/random | jq -r .content)
```

The reason the text isn't wrapping correctly is because ttyper splits files into "words" at newlines, not spaces and other whitespace. This is for a few reasons:

- It allows words to contain spaces.
- Splitting input into lines is standard for CLI tools, so it improves compatability.
- Lexical analysis is language specific. English words break at lots of characters like spaces, em-dashes, and en-dashes, whereas some languages (like Japanese) don't have any seperators between words besides punctuation.

As an example of the second point, you can make the text wrap correctly (most of the time) by also piping through `tr` to replace spaces with newlines:

```bash
ttyper <(curl -sSL https://api.quotable.io/random | jq -r .content | tr " " "\n")
```

**Comment by brian6932** [comment]
`/dev/stdin` is not a thing on Windows, this is not a natively supported feature, that is an OS feature, not a crossplatform feature
