### ISSUE TITLE
Don't show `worse keys` with 100% accuracy

### ISSUE THREAD

**Issue by getchup** [max-niederman/ttyper#94]
Currently ttyper shows a list of top 5 worse keys after you complete a test. However if you finish the test without making a mistake, ttyper still shows a list of 5 worse keys, even though they're all at 100% accuracy.

Are these now basically ranked as the top 5 slowest keys instead?

**Comment by max-niederman** [comment]
Currently, the order is indeterminate twice over: once because the order of a `std::collections::hash_map::Iter` is arbitrary and again because we use an unstable sort.

I'm not opposed to changing the behavior when there are keys in the top 5 with perfect accuracy, but what behavior would you like to see, exactly?

**Comment by getchup** [comment]
I was thinking of not showing anything when there are no mistakes tbh
